services:
  api:
    container_name: 'api'
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - db
    restart: on-failure
  db:
    image: redis:7
    environment:
      REDIS_PASSWORD: redis_pass
    ports:
      - 6379:6379
    volumes:
      - ./data:/data